services:
  - type: web
    name: speaksense-demo
    env: static
    buildCommand: echo "No build needed"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
